export const FETCH_PROVIDERS_START = 'FETCH_PROVIDERS_START';
export const FETCH_PROVIDERS_SUCCESS = 'FETCH_PROVIDERS_SUCCESS';
export const FETCH_PROVIDERS_FAIL = 'FETCH_PROVIDERS_FAIL';
export const FETCH_PROVIDERS = 'FETCH_PROVIDERS';

export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';
export const FETCH_SERVICES = 'FETCH_SERVICES';
